- name: Deploy Nginx Website configuration
  template:
    src: "./templates/nginx_confd.j2"
    dest: "/etc/nginx/conf.d/{{ fqdn }}.conf"
    owner: root
    group: root
    mode: 0644
- name: Delete default Website
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
- name: Restart niginx
  service:
    name: nginx
    state: restarted
