- name: Install needed Packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python3-pip
    - gcc

- name: Install needed pip modules
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - mysqlclient
